# Generated by Django 3.2.8 on 2021-11-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
