# Generated by Django 3.2.8 on 2021-11-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postcomment_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
